name: Pull Request title rules
on:
  pull_request:
    types:  [opened, edited, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request title rules
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '([0-9])+:([a-z])+' # Regex the title should match.
          allowed_prefixes: 'JIRA-'
          prefix_case_sensitive: true
