name: Pull Request title rules
on:
  pull_request:
    types:  [opened, edited, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request title rules
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '([0-9]+)(:.*)?' # 1234: This is an optional title
          allowed_prefixes: 'JIRA-' # JIRA-1234: This is an optional title
          prefix_case_sensitive: true # 'jira-' will not work. Must be 'JIRA-'
